CREATE TABLE DIETA (
                            ID NUMBER GENERATED by default on null as IDENTITY PRIMARY KEY,
                            NOMEDIETA VARCHAR2(200),
                            DTADIETA DATE,
                            TIPODIETA VARCHAR2(100),
                            DESCRICAO VARCHAR2(200),
                            SITUACAO NUMBER,
                            IDPACIENTE NUMBER,

                            FOREIGN KEY (IDPACIENTE) REFERENCES PACIENTE (ID)
)