CREATE TABLE ENDERECO(
                         ID NUMBER GENERATED by default on null as IDENTITY PRIMARY KEY,
                         CEP VARCHAR2(20),
                         CIDADE VARCHAR2(100),
                         ESTADO CHAR(2),
                         LOGRADOURO VARCHAR2(300),
                         NUMERO VARCHAR2(10),
                         COMPLEMENTO VARCHAR2(100),
                         BAIRRO VARCHAR2(100),
                         REFERENCIA VARCHAR2(100)
)
/
CREATE TABLE PACIENTE(
                         ID NUMBER GENERATED by default on null as IDENTITY PRIMARY KEY,
                         NOME VARCHAR2(200),
                         GENERO VARCHAR2(100),
                         DTANASCIMENTO DATE,
                         CPF VARCHAR2(20),
                         RG VARCHAR2(20),
                         ESTADOCIVIL VARCHAR2(20),
                         TELEFONE VARCHAR2(20),
                         EMAIL VARCHAR2(100),
                         NATURALIDADE VARCHAR2(100),
                         TELEMERGENCIA VARCHAR2(20),
                         CONVENIO VARCHAR2(200),
                         NROCONVENIO VARCHAR2(100),
                         VALCONVENIO DATE,
                         IDENDERECO NUMBER,

                         FOREIGN KEY (IDENDERECO) REFERENCES ENDERECO (ID)


)
