CREATE TABLE CONSULTA(
                         ID NUMBER GENERATED by default on null as IDENTITY PRIMARY KEY,
                         IDPACIENTE NUMBER,
                         MOTIVO VARCHAR2(200),
                         DTACONSULTA DATE,
                         PROBLEMA VARCHAR2(1024),
                         MEDICACAO VARCHAR2(4000),
                         PRECAUCAO VARCHAR2(4000),

                         FOREIGN KEY(IDPACIENTE) REFERENCES PACIENTE (ID)
)
