CREATE TABLE MEDICAMENTO(
                         ID NUMBER GENERATED by default on null as IDENTITY PRIMARY KEY,
                         DESCRICAO VARCHAR2(200),
                         DTAMEDICAMENTO DATE,
                         TIPO VARCHAR2(100),
                         UNIDADE VARCHAR2(10),
                         OBSERVACAO VARCHAR2(4000)
)
